language: node_js
node_js:
  - lts/*
before_install: 
  - export PATH=$PATH:`yarn global bin`
  - yarn global add greenkeeper-lockfile@1
install: yarn
before_script: greenkeeper-lockfile-update
script: yarn build:prod
after_script: greenkeeper-lockfile-upload
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN
    local_dir: dist
    skip_cleanup: true
    on:
      tags: true
  - provider: npm
    email: mats.pfeiffer@googlemail.com
    api_key: $NPM_TOKEN
    on:
      tags: true
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email:
    on_success: never
    on_failure: always
