language: node_js
node_js:
- node
before_deploy:
  yarn build:lib
deploy:
  provider: npm
  email: mats.pfeiffer@googlemail.com
  api_key: $NPM_TOKEN
  on:
    tags: true
cache:
  directories:
    - "node_modules"
  yarn: true  
notifications:
  email:
    on_success: never
    on_failure: always
